Parameters:
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC that you want to use the centralised endpoints in.
  AssumeRoleARN:
    Type: String
    Description: The Route53 Role in the Hub Account that allows us to Authorize a VPC to the Private Hosted Zone
  Route53HostedZoneIDSSM:
    Type: String
    AllowedPattern: ^[A-Z0-9]+$
    Description: The route53 hosted zone id from the hub stack for the the SSM service, the string before the colon in <route53 hosted zone id>:<regional vpc endpoint dns name>
  AssetParametersf3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797S3BucketBEE108A9:
    Type: String
    Description: S3 bucket for asset "f3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797"
  AssetParametersf3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797S3VersionKeyA877E3C9:
    Type: String
    Description: S3 key for asset version "f3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797"
  AssetParametersf3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797ArtifactHashAAFCA968:
    Type: String
    Description: Artifact hash for asset "f3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797"
Resources:
  R53Role778AB903:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/R53 Role/Resource
  R53RoleDefaultPolicy70517911:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - route53:AssociateVPCWithHostedZone
              - route53:DisassociateVPCFromHostedZone
              - ec2:DescribeVpcs
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: R53RoleDefaultPolicy70517911
      Roles:
        - Ref: R53Role778AB903
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/R53 Role/DefaultPolicy/Resource
  VpcAssociationAuthorizationssmCustomResourcePolicyA502D795:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Resource: arn:aws:iam::610408810780:role/ProServeApgCentralisedVpcEndpoints-R53Role778AB903-DK5I6NEW48MZ
        Version: "2012-10-17"
      PolicyName: VpcAssociationAuthorizationssmCustomResourcePolicyA502D795
      Roles:
        - Ref: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/VpcAssociationAuthorization-ssm/CustomResourcePolicy/Resource
  VpcAssociationAuthorizationssm48104BC2:
    Type: Custom::AWS
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd22872D164C4C
          - Arn
      Create:
        Fn::Join:
          - ""
          - - '{"action":"createVPCAssociationAuthorization","service":"Route53","assumedRoleArn":"arn:aws:iam::610408810780:role/ProServeApgCentralisedVpcEndpoints-R53Role778AB903-DK5I6NEW48MZ","parameters":{"HostedZoneId":"'
            - Ref: Route53HostedZoneIDSSM
            - '","VPC":{"VPCId":"'
            - Ref: VPCId
            - '","VPCRegion":"'
            - Ref: AWS::Region
            - '"}},"physicalResourceId":{"id":"createVPCAssociationAuthorization-ssm"}}'
      InstallLatestAwsSdk: true
    DependsOn:
      - VpcAssociationAuthorizationssmCustomResourcePolicyA502D795
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/VpcAssociationAuthorization-ssm/Resource/Default
  AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/AWS679f53fac002430cb0da5b7982bd2287/ServiceRole/Resource
  AWS679f53fac002430cb0da5b7982bd22872D164C4C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersf3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797S3BucketBEE108A9
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersf3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797S3VersionKeyA877E3C9
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersf3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797S3VersionKeyA877E3C9
      Role:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
          - Arn
      Handler: index.handler
      Runtime: nodejs12.x
      Timeout: 120
    DependsOn:
      - AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/AWS679f53fac002430cb0da5b7982bd2287/Resource
      aws:asset:path: asset.f3d3a3cc7f26921b237eff24fc5dd7aef8f0465a1f376b8f7918eb3d4b3e8797
      aws:asset:property: Code
  AssociateVPCWithHostedZonessmCustomResourcePolicy0E342EA3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - route53:AssociateVPCWithHostedZone
              - ec2:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: AssociateVPCWithHostedZonessmCustomResourcePolicy0E342EA3
      Roles:
        - Ref: AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2
    DependsOn:
      - VpcAssociationAuthorizationssmCustomResourcePolicyA502D795
      - VpcAssociationAuthorizationssm48104BC2
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/AssociateVPCWithHostedZone-ssm/CustomResourcePolicy/Resource
  AssociateVPCWithHostedZonessm59A0D915:
    Type: Custom::AWS
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - AWS679f53fac002430cb0da5b7982bd22872D164C4C
          - Arn
      Create:
        Fn::Join:
          - ""
          - - '{"action":"associateVPCWithHostedZone","service":"Route53","parameters":{"HostedZoneId":"'
            - Ref: Route53HostedZoneIDSSM
            - '","VPC":{"VPCId":"'
            - Ref: VPCId
            - '","VPCRegion":"'
            - Ref: AWS::Region
            - '"}},"physicalResourceId":{"id":"associateVPCWithHostedZone-ssm"}}'
      InstallLatestAwsSdk: true
    DependsOn:
      - AssociateVPCWithHostedZonessmCustomResourcePolicy0E342EA3
      - VpcAssociationAuthorizationssmCustomResourcePolicyA502D795
      - VpcAssociationAuthorizationssm48104BC2
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/AssociateVPCWithHostedZone-ssm/Resource/Default
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WPQW/CMAyFfwt3N1C47MiotHNVfoGXGpa1caTYEUJV/vuSMph28nvSe/bn1rT7vdltjniTxo7TdrEhklnOinaC7sI9RvSkFGEgCSlagi6JBv9nL/zS7yKkpXt1fIUusGhMVmukmNGpC5yhnlocerMMYX706+zD7Ox9vbmqDDP6zxELTNk2kwb+SGzrDniJkn7qDHJosAKIWTmKN6dkJ9ITCmWwK3cTf2FL6ib/f8nQ3/Ur8PZg3ky723yLc01MrM6TGR7zBwTIzc4yAQAA
    Metadata:
      aws:cdk:path: ProServeApgCentralisedVpcEndpointsSpokeStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

